<?php

function title_case_menu() {
    $items['title_case'] = array(
        'title' => 'We Can Title Case That!',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('title_case_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['title_case_success'] = array(
        'title' => 'Success!!',
        'page callback' => 'title_case_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function title_case_form() {
    $form['input'] = array(
        '#title' => 'User Input',
        '#type' => 'textfield',
        '#description' => t('Enter the sentence to be title cased here'),
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Case Me!',
    );

    return $form;
}

function title_case_form_submit($form, &$form_state) {
    $input = $form_state['values']['input'];

    //get user input
    //break string up into words with explode function
    //look at first letter in each word
    //make capital
    //recombine words into one string

    $list_of_words = explode(" ", $input);
    drupal_set_message($list_of_words[0]);
    $output = array();

    foreach($list_of_words as $word) {
        $capitalized_word = ucfirst($word);
        array_push($output, $capitalized_word);
    }

    $output = implode(" ", $output);

    $_SESSION['title_case_output'] = $output;
    $form_state['redirect'] = 'title_case_success';
}

function title_case_success() {
    return '<p>' . $_SESSION['title_case_output'] . '</p>';
}
