<?php

function title_case_menu() {
    $items['title_case'] = array(
        'title' => 'We Can Title Case That!',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('title_case_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['title_case_result'] = array(
        'title' => 'Result',
        'page callback' => 'title_case_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function title_case_form() {
    $form['input'] = array(
        '#title' => 'User Input',
        '#type' => 'textfield',
        '#description' => t('Enter the sentence to be title cased here'),
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Case Me!',
    );

    return $form;
}

function title_case_form_submit($form, &$form_state) {
    $input = $form_state['values']['input'];
    $_SESSION['title_case_output'] = $input;
    $form_state['redirect'] = 'title_case_success';
}

function title_case_success() {
    return '<p>' . $_SESSION['title_case_output'] . '</p>';
}
